baseURL = ""
languageCode = "be"
title = "Цэнтар беларускай культуры й супольнасьці ў Вільні"
theme = "ananke"
disqusShortname = "vilnia"

DefaultContentLanguage = "be"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.be]
    title = "Цэнтар беларускай супольнасьці й культуры ў Вільні"
    weight = 1
    contentDir = "content/be"
  [languages.lt]
    title = "Baltarusių bendruomenės ir kultūros centras Vilniuje"
    weight = 2
    contentDir = "content/lt"
  [languages.en]
    title = "Belarusian Community and Culture Center in Vilnius"
    weight = 3
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[permalinks]
post = "/:slug/"

[params]
  favicon = "images/VBM_logo.svg"
  site_logo = ""
  description = "Welcome to the Belarusian Community and Culture Center in Vilnius."
  facebook = "https://www.facebook.com/lutskevichmuseum/"
  instagram = "https://www.instagram.com/vilniaus20_by/"
  background_color_class = "bg-dark-gray"
  recent_posts_number = 2
  # mainSections = ["post"]
