backend:
  name: git-gateway
  branch: master


  media_folder: "static/images"
  public_folder: "images"

  collections:
    - name: "vilnia"
    label: "Vilnia"
    folder: "content/be"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}